#!/bin/sh

main() {
	parse_opts "$@"

	if [ "$(command -v eix | wc -l)" -ge 1 ]; then
		if [ -n "$depclean" ]; then
			eix --color=never --selected -Ic --pure-packages |
				dmenu -i -l 10 | cut -d ' ' -f2 | xargs emerge $@
		elif [ -n "$unmerge" ]; then
			eix --color=never -Ic --pure-packages |
				dmenu -i -l 10 | cut -d ' ' -f2 | xargs emerge $@
		else
			eix --color=never -c --pure-packages |
				dmenu -i -l 10 | cut -d ' ' -f2 | xargs emerge $@
		fi
	elif [ "$(command -v q | wc -l)" -ge 1 ]; then
		if [ -n "$depclean" -o -n "$unmerge" ] ; then
			qlist -CIq | dmenu -i -l 10 | xargs emerge $@
		else
			qsearch -Caq | dmenu -i -l 10 | cut -d ':' -f1 | xargs emerge $@
		fi
	else
		printf '%s\n' "You have neither eix nor portage-utils installed."
	fi
}

help() {
	printf 'Usage:\t%s' "dmerge [options] [atoms]

Any emerge options and atoms will work.
"; }

parse_opts() {
	while [ $# -gt 0 ]; do
		key="$1"
		case $key in
			-h|--help) help ; exit 0 ;;
			-c|--depclean) depclean=1 ; shift ;;
			-C|--unmerge) unmerge=1 ; shift ;;
			*) shift ;;
		esac
	done
}

main "$@"
