#!/bin/sh

main() {
    parse_opts "$@"

    if [ -n "$help" ]; then
	help
    elif [ "$(command -v eix | wc -l)" -ge 1 ]; then
	if [ -n "$depclean" ]; then
	    eix --color=never --selected -Ic --pure-packages | dmenu -i -l 10 | cut -d ' ' -f2 | xargs -I {} doas emerge $@ {}
	elif [ -n "$unmerge" ]; then
	    eix --color=never -Ic --pure-packages | dmenu -i -l 10 | cut -d ' ' -f2 | xargs -I {} doas emerge $@ {}
	else
	    eix --color=never -c --pure-packages | dmenu -i -l 10 | cut -d ' ' -f2 | xargs -I {} doas emerge $@ {}
	fi
    elif [ "$(command -v q | wc -l)" -ge 1 ]; then
	if [ -n "$depclean" -o -n "$unmerge" ] ; then
	    qlist -CIq | dmenu -i -l 10 | xargs -I {} doas emerge $@ {}
	else
	    qsearch -Caq | dmenu -i -l 10 | cut -d ':' -f1 | xargs -I {} doas emerge $@ {}
	fi
    else
	printf "You don't have neither eix nor portage-utils installed. One of them is required. Install one of them.\n"
    fi
}

help() {
    printf "Usage:	dmerge [options] [atoms]

Any emerge options will work. Any emerge atoms will also work.\n"
}

parse_opts() {
    while [ $# -gt 0 ]; do
        key="$1"
        case $key in
        -h|--help)
            help=1
            shift
            ;;
        -c|--depclean)
            depclean=1
            shift
            ;;
	-C|--unmerge)
	    unmerge=1
	    shift
	    ;;
	*)
	    shift
	    ;;
	esac
    done
}

main "$@"
